metadata_dir = "/data/meta"
data_dir = "/data/data"
db_engine = "sqlite"

# Replication must be 1 for a single-node setup
replication_factor = 1

# Internal RPC
rpc_bind_addr = "[::]:3901"
rpc_secret = "f49de2bb8725f3bacf69b92b4a83582e6fbc53ed289da9f694c828efa9ad836d"

[s3_api]
api_bind_addr = "[::]:9000"
s3_region = "us-east-1"

[s3_web]
bind_addr = "[::]:9001"
root_domain = ".localhost"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "admin_secret_token"